/**
 * Client-side formatter that replicates the core formatter logic.
 * This avoids re-fetching from the API when the user switches formats.
 *
 * The raw skill content (from skill.content) is in claude-skill / claude-skill
 * format (markdown with frontmatter). Other formats strip frontmatter and
 * add their own header.
 */

export type Format = 'claude-skill' | 'cursor-rules' | 'windsurf-rules';

export interface FormattedSkill {
  content: string;
  filename: string;
  format: Format;
}

function stripFrontmatter(content: string): string {
  return content.replace(/^---[\s\S]*?---\n*/m, '');
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

export function formatSkill(
  rawContent: string,
  name: string,
  sourceTitle: string,
  sourceUrl: string,
  format: Format,
): FormattedSkill {
  switch (format) {
    case 'claude-skill':
      return {
        content: rawContent,
        filename: `${name}.md`,
        format: 'claude-skill',
      };

    case 'cursor-rules': {
      const body = stripFrontmatter(rawContent);
      const header = `# Cursor Rules — ${sourceTitle}\n# Source: ${sourceUrl}\n# Generated by SkillJack (skilljacked.com)\n\n`;
      return {
        content: header + body,
        filename: '.cursorrules',
        format: 'cursor-rules',
      };
    }

    case 'windsurf-rules': {
      const body = stripFrontmatter(rawContent);
      const header = `# Windsurf Rules — ${sourceTitle}\n# Source: ${sourceUrl}\n# Generated by SkillJack (skilljacked.com)\n\n`;
      return {
        content: header + body,
        filename: '.windsurfrules',
        format: 'windsurf-rules',
      };
    }

    default:
      return {
        content: rawContent,
        filename: `${name}.md`,
        format: 'claude-skill',
      };
  }
}
