import { StructuredSkill } from '../transformer/types';
import { FormattedOutput } from './types';

function stripFrontmatter(content: string): string {
  return content.replace(/^---[\s\S]*?---\n*/m, '');
}

export function formatWindsurfRules(skill: StructuredSkill): FormattedOutput {
  const body = stripFrontmatter(skill.content);
  const header = `# Windsurf Rules — ${skill.sourceTitle}\n# Source: ${skill.sourceUrl}\n# Generated by SkillJack (skilljacked.com)\n\n`;

  return {
    content: header + body,
    filename: '.windsurfrules',
    format: 'windsurf-rules',
  };
}
