import Anthropic from '@anthropic-ai/sdk';
import { TransformError } from '../utils/errors';
import { withRetry, type RetryOpts } from '../utils/retry';
import {
  EVAL_CRITERIA,
  tallyVerdicts,
  pickSkillLabel,
  type CriterionVerdict,
  type SkillLabel,
  type EvalTally,
} from './scoring';

// The two outputs under comparison are generated by the model the product
// actually ships, because the question is whether the SKILL helps -- not which
// model is better. The judge is a stronger model, since the verdict is the part
// that has to be trustworthy. Change either here, not at the call sites.
const GENERATION_MODEL = 'claude-sonnet-5';
const JUDGE_MODEL = 'claude-opus-5';

const GENERATION_TIMEOUT_MS = 60_000;
const JUDGE_TIMEOUT_MS = 90_000;
const GENERATION_MAX_TOKENS = 4096;
const JUDGE_MAX_TOKENS = 8192;

const JUDGE_SYSTEM_PROMPT = `You are comparing two responses to the same prompt, written by two different assistants.

You will judge them on five criteria: completeness, specificity, correctness, clarity, and adherence to the user's request.

For each criterion, decide whether response A is better, response B is better, or they are equivalent.

Rules:
- Judge only what is in front of you. Do not speculate about how either response was produced.
- "tie" is a real answer. Use it when the two are genuinely comparable on that criterion; do not manufacture a preference.
- Judge each criterion independently. A response that wins on clarity may lose on correctness.
- Length is not quality. A longer response is not automatically more complete.

Submit your verdicts with the submit_verdicts tool.`;

export interface EvaluateSkillInput {
  skillName: string;
  skillContent: string;
  testPrompt: string;
}

export interface EvaluateSkillOpts {
  apiKey?: string;
  maxRetries?: number;
  onRetry?: (msg: string) => void;
  /** Injectable for tests; defaults to Math.random. */
  random?: () => number;
}

export interface SkillEvalResult {
  score: number;
  tally: EvalTally;
  verdicts: CriterionVerdict[];
  /** Which label the skill output was shown under — recorded so a stored result stays interpretable. */
  skillLabel: SkillLabel;
  baselineOutput: string;
  skillOutput: string;
  reasoning: string;
}

function textOf(response: Anthropic.Message): string {
  const block = response.content.find((b) => b.type === 'text');
  if (!block || block.type !== 'text') {
    throw new TransformError('The model returned no text output.', { kind: 'parse' });
  }
  return block.text;
}

async function generate(
  client: Anthropic,
  prompt: string,
  system: string | undefined,
): Promise<string> {
  const response = await client.messages.create(
    {
      model: GENERATION_MODEL,
      max_tokens: GENERATION_MAX_TOKENS,
      ...(system ? { system } : {}),
      messages: [{ role: 'user', content: prompt }],
    },
    { signal: AbortSignal.timeout(GENERATION_TIMEOUT_MS) },
  );
  return textOf(response);
}

/**
 * The judge answers through a forced tool call rather than free-form JSON.
 *
 * The installed SDK predates the structured-output parameter, and asking for
 * JSON in prose leaves the parse to chance. A tool with a closed enum schema
 * plus tool_choice makes a malformed verdict a schema violation instead of a
 * parsing problem.
 *
 * Thinking is deliberately left at the model's default rather than disabled:
 * with thinking off, the model can write a tool call into its visible text
 * instead of emitting a tool_use block, which would break this entirely.
 */
const VERDICT_TOOL: Anthropic.Tool = {
  name: 'submit_verdicts',
  description: 'Submit one verdict per criterion, plus a short rationale.',
  input_schema: {
    type: 'object',
    properties: {
      verdicts: {
        type: 'array',
        description: 'Exactly one entry per criterion.',
        items: {
          type: 'object',
          properties: {
            criterion: { type: 'string', enum: [...EVAL_CRITERIA] },
            verdict: {
              type: 'string',
              enum: ['A', 'B', 'tie'],
              description: 'Which response is better on this criterion.',
            },
          },
          required: ['criterion', 'verdict'],
        },
      },
      reasoning: {
        type: 'string',
        description: 'Two or three sentences explaining the overall judgement.',
      },
    },
    required: ['verdicts', 'reasoning'],
  },
};

interface JudgeOutput {
  verdicts: CriterionVerdict[];
  reasoning: string;
}

async function judge(
  client: Anthropic,
  testPrompt: string,
  outputA: string,
  outputB: string,
): Promise<JudgeOutput> {
  const response = await client.messages.create(
    {
      model: JUDGE_MODEL,
      max_tokens: JUDGE_MAX_TOKENS,
      system: JUDGE_SYSTEM_PROMPT,
      tools: [VERDICT_TOOL],
      tool_choice: { type: 'tool', name: 'submit_verdicts' },
      messages: [
        {
          role: 'user',
          content: `The prompt both assistants were given:\n\n${testPrompt}\n\n---\n\nResponse A:\n\n${outputA}\n\n---\n\nResponse B:\n\n${outputB}`,
        },
      ],
    },
    { signal: AbortSignal.timeout(JUDGE_TIMEOUT_MS) },
  );

  const toolUse = response.content.find((b) => b.type === 'tool_use');
  if (!toolUse || toolUse.type !== 'tool_use') {
    throw new TransformError('The judge did not return a verdict.', { kind: 'parse' });
  }

  // Tool input arrives as parsed JSON, but it is still model output — validate
  // the shape rather than trusting it.
  const input = toolUse.input as { verdicts?: unknown; reasoning?: unknown };
  if (!Array.isArray(input.verdicts)) {
    throw new TransformError('The judge returned no verdicts.', { kind: 'parse' });
  }

  const allowed = new Set<string>(EVAL_CRITERIA);
  const verdicts: CriterionVerdict[] = [];
  for (const raw of input.verdicts) {
    const entry = raw as { criterion?: unknown; verdict?: unknown };
    if (
      typeof entry.criterion === 'string' &&
      allowed.has(entry.criterion) &&
      (entry.verdict === 'A' || entry.verdict === 'B' || entry.verdict === 'tie')
    ) {
      verdicts.push({
        criterion: entry.criterion as CriterionVerdict['criterion'],
        verdict: entry.verdict,
      });
    }
  }

  if (verdicts.length === 0) {
    throw new TransformError('The judge returned no usable verdicts.', { kind: 'parse' });
  }

  return {
    verdicts,
    reasoning: typeof input.reasoning === 'string' ? input.reasoning : '',
  };
}

/**
 * Run one skill against one test prompt and score whether it helped.
 *
 * Three model calls: the prompt alone, the prompt with the skill in the system
 * prompt, and one blind comparison of the two. Never called automatically --
 * evaluating on every extraction would cost more per jack than the tier earns.
 */
export async function evaluateSkill(
  input: EvaluateSkillInput,
  opts: EvaluateSkillOpts = {},
): Promise<SkillEvalResult> {
  const client = new Anthropic({ apiKey: opts.apiKey });
  const retryOpts: RetryOpts = { maxRetries: opts.maxRetries ?? 1, onRetry: opts.onRetry };

  // Both generations run concurrently; neither depends on the other.
  const [baselineOutput, skillOutput] = await Promise.all([
    withRetry(() => generate(client, input.testPrompt, undefined), retryOpts),
    withRetry(
      () =>
        generate(
          client,
          input.testPrompt,
          `You have been given the following skill. Apply it when responding.\n\n${input.skillContent}`,
        ),
      retryOpts,
    ),
  ]);

  // Randomise which side the skill output is shown as, and keep the mapping.
  const skillLabel = pickSkillLabel(opts.random);
  const outputA = skillLabel === 'A' ? skillOutput : baselineOutput;
  const outputB = skillLabel === 'A' ? baselineOutput : skillOutput;

  const { verdicts, reasoning } = await withRetry(
    () => judge(client, input.testPrompt, outputA, outputB),
    retryOpts,
  );

  const tally = tallyVerdicts(verdicts, skillLabel);

  return {
    score: tally.score,
    tally,
    verdicts,
    skillLabel,
    baselineOutput,
    skillOutput,
    reasoning,
  };
}

export {
  EVAL_CRITERIA,
  tallyVerdicts,
  pickSkillLabel,
  type CriterionVerdict,
  type EvalCriterion,
  type Verdict,
  type SkillLabel,
  type EvalTally,
} from './scoring';
